"""Provider verification against contracts generated by the consumer suite."""

from pathlib import Path
from typing import Any, Literal

import pytest
from pact import Verifier

from contract_framework.provider import repository

PROJECT_ROOT = Path(__file__).resolve().parents[2]
PACT_DIR = PROJECT_ROOT / "pacts"


def user_exists(
    action: Literal["setup", "teardown"],
    parameters: dict[str, Any] | None,
) -> None:
    values = parameters or {}
    user_id = int(values.get("id", 123))
    if action == "setup":
        repository.put_user(
            user_id=user_id,
            name=str(values.get("name", "Alice")),
            email=str(values.get("email", "alice@example.com")),
        )
    elif action == "teardown":
        repository.delete_user(user_id)


def user_does_not_exist(
    action: Literal["setup", "teardown"],
    parameters: dict[str, Any] | None,
) -> None:
    if action == "setup":
        repository.delete_user(int((parameters or {}).get("id", 999)))


def provider_accepts_creation(
    action: Literal["setup", "teardown"],
    parameters: dict[str, Any] | None,
) -> None:
    del parameters
    if action == "setup":
        repository.reset()


@pytest.mark.provider_contract
def test_user_provider_honors_consumer_contract(provider_url: str) -> None:
    pact_files = list(PACT_DIR.glob("*.json"))
    assert pact_files, (
        "No Pact file found. Run `pytest tests/consumer` before provider verification."
    )

    verifier = (
        Verifier("user-provider", host="127.0.0.1")
        .add_source(PACT_DIR)
        .add_transport(url=provider_url)
        .state_handler(
            {
                "user exists": user_exists,
                "user does not exist": user_does_not_exist,
                "provider accepts user creation": provider_accepts_creation,
            },
            teardown=True,
        )
    )

    verifier.verify()
